### ISSUE TITLE
Integration with jenkins or some other build system

### ISSUE THREAD

**Issue by MiguelCastillo** [MiguelCastillo/scenic#4]
I had integrations with jenkins until they decided to require me to provide a credit card to use the free version.  So I need to find an alternative that integrates with github so that build and tests can run when making PRs and pushing commits.

**Comment by jandrade** [comment]
What do you think about using GitHub actions? I've been using it a lot lately and it's super convenient (and free for public repos).

What checks are needed to run?

**Comment by MiguelCastillo** [comment]
yeah thats definitely a great alternative!  i think we want `npm test` and another one for linting.

**Comment by jandrade** [comment]
Awesome! do you mind if I take this issue? or are you interested on this integration? either option works for me!

**Comment by MiguelCastillo** [comment]
yeah github pages definitely are a great option.  let's do it!  feel free to pick it up, I dont mind it at all.
